### ISSUE TITLE
Note about hvm-core easy to overlook

### ISSUE THREAD

**Issue by renxida** [HigherOrderCO/bend#301]
This note is in rather small font and is really easily overlooked. Ideally the examples on README.md on the main branch should just work. Otherwise, at least the warning should be put in big red letters like

$${\color{red} \text{WARNING}: }$$ If you want to use Bend right now, use branch  [hvm-core](https://github.com/HigherOrderCO/bend/tree/hvm-core), as the latest version of Bend targets an unreleased version of HVM.

----
- [ ] fib.bend]
<details>

```
@renxida ➜ /workspaces/myhvm $ bend --version
bend 0.1.0
@renxida ➜ /workspaces/myhvm $ hvm --version
hvm 1.0.11
@renxida ➜ /workspaces/myhvm $ cat fib.bend
add = λa λb (+ a b)

fib = λx switch x {
  0: 1
  _: let p = x-1; switch p {
    0: 1
    _: (+ (fib p) (fib p-1))
  }
}

main = (fib 30)@renxida ➜ /workspaces/myhvm $ bend run fib.bend
Errors:
Error reading result from hvm. Output :
Expected `Term`:
  2 | HVM_MAIN_CALL = .out.hvm
exit status: 1

@renxida ➜ /workspaces/myhvm $ bend compile fib.bend
Warnings:
In definition 'add':
  Definition is unused.

@add = ($(:[+] $(a b)) (a b))

@fib = (?((1 @fib__C1) a) a)

@fib__C0 = ({$([+1] a) b} d)
  & @fib ~ (a $(:[+] $(c d)))
  &! @fib ~ (b c)

@fib__C1 = (?((1 @fib__C0) a) a)

@main = a
  & @fib ~ (30 a)
@renxida ➜ /workspaces/myhvm $
```

</details>

- [ ] add example from README.md (the first example in the readme)
<details>
![image]
(https://github.com/HigherOrderCO/bend/assets/10362952/94ac4673-be76-4ad7-adf3-abbfbddc92f5)
```
@renxida ➜ /workspaces/myhvm $ bend --version
bend 0.1.0
@renxida ➜ /workspaces/myhvm $ hvm --version
hvm 1.0.11
@renxida ➜ /workspaces/myhvm $ bend run add.bend
Errors:
In add.bend :
- expected: '('
- detected:
  1 | def main:

@renxida ➜ /workspaces/myhvm $ cat add.bend
def main:
  return 2 + 3
@renxida ➜ /workspaces/myhvm $ 
```
</details>

**Comment by developedby** [comment]
That was super temporary. HVM2 is now released, so we don't need it anymore https://github.com/HigherOrderCO/hvm
