### ISSUE TITLE
Empty switch causes panic instead of syntax error

### ISSUE THREAD

**Issue by mushchlo** [HigherOrderCO/bend#315]
When comiling `main = switch {}`, there is no parse error for an empty switch statement, so the compiler panics when unwrapping last_mut() in children_mut_with_binds.

`thread 'main' panicked at src/fun/mod.rs:656:51:
called 'Option::unwrap()' on a 'None' value`

A proper error message would be nice.

**Comment by developedby** [comment]
Fixed.
Thank you for your report
