### ISSUE TITLE
Inaccurate description for the first code sample on README 

### ISSUE THREAD

**Issue by fabiolimath** [HigherOrderCO/Bend#322]
Hi!

I believe the description for the first code sample on README is slightly incorrect. Below the code one can read:

`This code adds all numbers from 0 to 2^30`

But, it's sums the numbers till 2^30, but not the 2^30 itself. For example:

`sum(3,0)`

will return 28. But the sum from zero to 2^3=8 is, in fact, (1+2+3+4+5+6+7+8)=36. Although, 28+8=36.

**Comment by developedby** [comment]
It's very common to talk about numbers ranges as not including the last element, but I'll adjust the wording to be more precise

**Comment by developedby** [comment]
Closed by #324
