### ISSUE TITLE
Operator Precedence Bug (Exponentiation)

### ISSUE THREAD

**Issue by asras** [HigherOrderCO/Bend#323]
EDIT: During the writing of this issue I noticed two additional things:
1. There seems to be some floating point inaccuracy in general.
2. There is some discrepancy in floating point results between `bend run` and `bend run-c`.

I don't know if those are worthy of separate issues. /EDIT

The example in GUIDE.md with area calculation reveals an operator precedence bug:

```
type Shape:
  Circle { radius }
  Rectangle { width, height }

def area(shape):
  match shape:
    case Shape/Circle:
      return 3.14 * shape.radius ^ 2.0
    case Shape/Rectangle:
      return shape.width * shape.height

def main:
  return area(Shape/Circle { radius: 10.0 })
```

This program returns 985.938 = (3.14 * 10.0)^2.0 and not 313.996 = 3.14 * (10.0^2.0), as expected. Tested with `bend run` and `bend run-c` on Apple M2. Both numbers also deviate from what you get with python.

An additional note is that I get slightly different results with `run` and `run-c`, when I replace

`return 3.14 * shape.radius ^ 2.0 -> return 3.14 * (shape.radius ^ 2.0)`

**Comment by developedby** [comment]
The results will inevitably be different because we use a 24 bit representation as opposed to 64 bit floats in python. There is also some bugs in the float implementation we're currently fixing.

For the exponentiation, we added `**` which has the right precedence, keeping `^` for bitwise xor. We're currently updating the documentation

**Comment by asras** [comment]
Alright, thank you for the explanation! Let me just add that I think HVM/Bend is an amazing idea, keep up the good work.
