### ISSUE TITLE
Working with AMD ROCm

### ISSUE THREAD

**Issue by mbido** [HigherOrderCO/Bend#371]
**Is your feature request related to a problem? Please describe.**
My computer has an AMD GPU and so I can only use "bend run-c" 

**Describe the solution you'd like**
Would it be possible one day to get a compilation for ROCm (I know it is not an easy task)

**Additional context**
I never really did some research on ROCm and CUDA so my request may be a bit naïve.

**Comment by kings177** [comment]
We do plan on adding support to other platforms too, but right now out priority is perfect the CUDA version.

Closing since duplicate of https://github.com/HigherOrderCO/Bend/issues/341
