### ISSUE TITLE
Request: support for 32/64 bit integers

### ISSUE THREAD

**Issue by MrOnlineCoder** [HigherOrderCO/Bend#375]
**Is your feature request related to a problem? Please describe.**
I want to use Bend to perform some parallel computations for a research paper, however, the values used in it do not fit into a 24-bit integer, therefore I would need at least 32-bit integers, at most - 64-bits.

**Describe the solution you'd like**
Support of 32 or 64 bit integers in Bend/HVM. Due to untyped nature of the language, maybe this can be configured per program via a flag.

**Describe alternatives you've considered**
OpenCL or manual CUDA code

**Comment by kings177** [comment]
Thank you for the issue, we do plan on releasing a 64bit version of HVM in the near future.

Redirecting since this is HVM related
