### ISSUE TITLE
Using structs instead of enums

### ISSUE THREAD

**Issue by AlexDevFlow** [HigherOrderCO/Bend#377]
Hello there, this project looks incredible! Had a quick look at the code and found out a thing, that could be correct, but at the same time here is an alternative would make sense, let me know what you think!

**Is your feature request related to a problem? Please describe.**
`Expr` and `Stmt` types are defined as `enums`, which can make it difficult to work with their data fields. Accessing fields requires pattern matching or using tuple indexing, which can be error-prone.

**Describe the solution you'd like**
Using `structs` instead of  `enums` so that each variant's fields can be named and accessed directly.

**Describe alternatives you've considered**
One alternative would be to keep using enums but add helper methods or functions to access the fields in a more convenient way. However, this would very likely just add an extra layer of indirection and complexity.

An example where this could be done is in [src/imp/mod.rs](https://github.com/HigherOrderCO/Bend/blob/main/src/imp/mod.rs)

Hope this helps!

**Comment by developedby** [comment]
What do you mean using a struct? They fundamentally sum types. I could make each variant of the enum hold a struct but that would not be helpful.
Structuring code aroung pattern matching is done on purpose and is how we want to write this compiler.

**Comment by AlexDevFlow** [comment]
I understand, now that you've explained your idea behind the code, it makes sense, thank you!
