### ISSUE TITLE
Bend-Lang Install Compilation Failure

### ISSUE THREAD

**Issue by JoshnaksPNG** [HigherOrderCO/Bend#390]
**Describe the bug**
I've been trying to bend through rustup, as suggested in the README. However, when I run cargo +nightly install bend-lang, I get a compilation error with the following output. https://gist.github.com/JoshnaksPNG/381755bd687c16ac1b1f1351bc3fc96d

Three of these errors say that certain features may not be used on the stable release channel, but I am currently using rust nightly as default. Specifically nightly-x86_64-unknown-linux-gnu and cargo 1.80.0-nightly

**To Reproduce**
1. run cargo +nightly install bend-lang
2. Produces Errror [cargo +nightly install bend-lang](https://gist.github.com/JoshnaksPNG/381755bd687c16ac1b1f1351bc3fc96d)

**Expected behavior**
describe the expected behavior.

**Desktop (please complete the following information):**
 - OS:   Ubuntu running on WSL2
 - CPU: AMD Ryzen 7 5700G
 - GPU: Ryzen 7 5700G embedded graphics

**Additional context**
I followed the **Using Bend** section of the README.

**Comment by developedby** [comment]
If you do cargo +nightly --version what shows up?

**Comment by pedrohaveloso** [comment]
Tive o mesmo problema ao tentar instalar, também seguindo o passo a passo exemplificado no README.
Os mesmos erros: [bend-lang-install-error](https://gist.github.com/pedrohaveloso/b1765ab234e715641466883101c40591).

Utilizando:

- OS: Ubuntu 23.10;
- CPU: AMD Ryzen 3 2200G;
- GPU: GTX 1050 OC;
- Rust Nightly 1.80.0.

**Comment by pedrohaveloso** [comment]
> If you do cargo +nightly --version what shows up?

Tive o mesmo problema ao tentar instalar, também seguindo o passo a passo exemplificado no README.
Os mesmos erros: [bend-lang-install-error](https://gist.github.com/pedrohaveloso/b1765ab234e715641466883101c40591).

Utilizando:

OS: Ubuntu 23.10;
CPU: AMD Ryzen 3 2200G;
GPU: GTX 1050 OC;
Rust Nightly 1.80.0.

**Comment by JoshnaksPNG** [comment]
> If you do cargo +nightly --version what shows up?

This is the output for my cargo version

cargo 1.80.0-nightly (0de7f2ec6 2024-05-17)

**Comment by JoshnaksPNG** [comment]
Update: Package install now works after reinstall of Ubuntu on WSL2. Followed instructions again, but what the initial issue was is unclear.

Not closing this issue, because it looks like @pedrohaveloso is having the same issue on a non-wsl version of Ubuntu.

**Comment by kings177** [comment]
@pedrohaveloso what does your `rustup show` shows in "active toolchains"?

**Comment by pedrohaveloso** [comment]
> @pedrohaveloso what does your `rustup show` shows in "active toolchains"?


```bash
[...]

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.80.0-nightly (d84b90375 2024-05-19)
```

**Comment by pedrohaveloso** [comment]
> @pedrohaveloso what does your `rustup show` shows in "active toolchains"?

@kings177 

> @pedrohaveloso what does your `rustup show` shows in "active toolchains"?


```bash
[...]

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.80.0-nightly (d84b90375 2024-05-19)
```

**Comment by pedrohaveloso** [comment]
@kings177 Dessa forma funcionou. Obrigado 😊.

**Comment by developedby** [comment]
It seems like `cargo +nightly install` is not pulling the correct version for some reason, although `cargo +nightly --version` is, very mysterious

**Comment by developedby** [comment]
Since we don't need nightly anymore this is fixed, right? Can I close this @JoshnaksPNG
