### ISSUE TITLE
(Question) Advantages over CUDA

### ISSUE THREAD

**Issue by hardBSDk** [HigherOrderCO/Bend#392]

**Comment by partylikeits1983** [comment]
none

**Comment by developedby** [comment]
Writing CUDA is hard. If you want to anything non-trivial that isn't just linear algebra, it's very hard.
To run any possible high-level problem using non-trivial communication, anything symbolic and abstract, etc, is extremely hard.

But Bend lets you do just that. You write a normal high-level program with no threads, no locks, no memory handling, no core to core communication and it works **and** gets automatically parallelized to efficiently use the GPU resources.

Bend is not a competitor to CUDA. Fast CUDA programs will continue to be faster in CUDA.
