### ISSUE TITLE
(Question) This language is GPU-agnostic?

### ISSUE THREAD

**Issue by hardBSDk** [HigherOrderCO/Bend#393]
Does it run on any GPU? be it Intel, AMD, NVIDIA or ARM?

**Comment by SquarishRectangle** [comment]
Not completely sure what's going on behind the scenes but the documentation currently only lists a CUDA runtime for GPUs.

**Comment by developedby** [comment]
The language is GPU agnostic, but currently we only have a CUDA runtime. So only Nvidia gpus are supported, but we plan on adding other gpus in the future.
Duplicate of https://github.com/HigherOrderCO/Bend/issues/341
