### ISSUE TITLE
(Request) Tree-Sitter grammar of Bend

### ISSUE THREAD

**Issue by GabrielBarbosaGV** [HigherOrderCO/Bend#398]
Hello, everyone! I hope you are doing well.

I'd like to know if a Tree-Sitter grammar is available (or under development) to get some basic syntax highlighting with NeoVim.

Many thanks!

**Comment by developedby** [comment]
Not yet. I've seen some people on our discord who were looking to make one, so I recommend you joing the discord, search for vim or neo-vim and talk with them

**Comment by developedby** [comment]
Someone made it here https://github.com/LaBatata101/tree-sitter-bend.git with the vim script here https://github.com/SergioBonatto/bend-vim
