### ISSUE TITLE
Floating points don't work correctly

### ISSUE THREAD

**Issue by Ullreich** [HigherOrderCO/Bend#402]
By accident I found that arithmetic with 0.0 do not work correctly e.g. running
```
def main():
  return 1.0 + 0.0
```
with `run` or `run-c` errors out with:
```
assertion failed: expo >= -63 && expo <= 63
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
exit status: 101
```

I tried out a few things (not extensively) and found:

# Works:

* addition:
    * 0.0 + x.0
* subtraction:
    * 0.0 - x.0

# Errors with error above:

for any float x.0 != 0.0

* addition:
    * x.0 + 0.0
    * -x.0 + 0.0
* subtraction:
    * x.0 - x.0
    * x.0 - 0.0
* multiplication:
    * 0.0 * x.0 (doesn't  error but returns -2.000 for any 0.0 * x if run with `run-c`)
    * x.0 * 0.0
* division:
    * x.0 / 0.0 (expected to error a division by zero error, I would assume)
    * 0.0 / x.0 (doesn't  error but returns -2.000 for any 0.0 / x if run with `run-c`)

Perhaps related to https://github.com/HigherOrderCO/Bend/issues/387 ?

My setup:
* bend-lang 0.2.7
* Linux (Debian 12)
* Intel i7-8750H

**Comment by developedby** [comment]
We're aware and already are preparing a fix for it (floats are broken in other ways too, that'll all be solved hopefully tommorow).
We're tracking this issue in the HVM repository here https://github.com/HigherOrderCO/HVM/issues/285

**Comment by developedby** [comment]
Fixed in https://github.com/HigherOrderCO/HVM/pull/317
