### ISSUE TITLE
example of recursive sum

### ISSUE THREAD

**Issue by raybellwaves** [HigherOrderCO/Bend#405]
In the HVM repo there is an example of the language (https://github.com/HigherOrderCO/HVM?tab=readme-ov-file#language). I would like to know the bend equivalent of that.

It would be good if there was a HVM to Bend CLI parser e.g. `hvm_to_bend file.hvm file.bend` to automate this translation

**Comment by lucifer1004** [comment]
Actually there is one in https://github.com/HigherOrderCO/bend/blob/main/GUIDE.md

```python
def main():
  bend d = 0, i = 0:
    when d < 28:
      sum = fork(d+1, i*2+0) + fork(d+1, i*2+1)
    else:
      sum = i
  return sum
```

**Comment by developedby** [comment]
HVM to Bend can't be done right now because we need context that is only available during compilation.
We could add this metadata in the generated hvm, but that's not planned for now.
