### ISSUE TITLE
Clarification - does it uses virtual threads under the hood?

### ISSUE THREAD

**Issue by sanjeevirajm** [HigherOrderCO/Bend#417]
splitting the operations using tree structure sounds interesting.

i am curious how does that work.

Threads are heavily criticised, because it is bound to system hardware and it's operations are expensive.

In some cases, trying to do operations in parallel using threads decreases performance.

Light weight threads/Virtual threads/Coroutines came after that. 

Does bend or the runtime uses something like virtual threads to overcome issues in threads?

**Comment by developedby** [comment]
The C runtime of HVM uses normal threads with the pthread library. They are basically always running with a work pool strategy.
Not sure how virtual threads are supposed to make a difference in this case.
