### ISSUE TITLE
Floor Integer Division

### ISSUE THREAD

**Issue by navvye** [HigherOrderCO/Bend#426]
I was wondering if Bend natively supported floor integer division, similar to `//` in Python.

Some examples: 

`19//2 = 9`
`108/8 = 13` 

 If C had a typeof function, something similar to `(typeof (a /b)) floor(a / b) == a / b`. Right now, I believe the only way to do floor integer division is via a switch/case argument, which isn't user friendly.

**Comment by developedby** [comment]
Division between integers already truncates
```py
# Returns 1
def main:
  return 3 / 2
```
