### ISSUE TITLE
Error running Hello World

### ISSUE THREAD

**Issue by TheSimicSlaw** [HigherOrderCO/Bend#440]
I'm running on WSL Ubuntu. I downloaded Bend using "npm install -g bend", and everything seemed to work. I then created a basic main.bend file to test and make sure it was working. I copied the code from the GUIDE section:

--

def main():
  return "Hello, world!"

--

And then I put in the command "bend run main.bend" and got this error:

--

internal/fs/utils.js:269
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'run'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at Object.main (/mnt/c/Users/ryana/AppData/Roaming/npm/node_modules/bend/lib/bend.js:5223:31)
    at Object.<anonymous> (/mnt/c/Users/ryana/AppData/Roaming/npm/node_modules/bend/bin/bend:5:69)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'run'
}

--

I looked into the source code and couldn't find any issues, so I tried downloading it the other way with rust nightly. The download went well, no issues, but when I ran it I got the same issues.

**Comment by developedby** [comment]
Bend is a Rust program that you install with Cargo, not with npm.

> To use Bend, first, **install [Rust nightly](https://www.oreilly.com/library/view/rust-programming-by/9781788390637/e07dc768-de29-482e-804b-0274b4bef418.xhtml)**. Then, install HVM2 and Bend itself with:
>
>**cargo** +nightly install hvm
>**cargo** +nightly install bend-lang

**Comment by TheSimicSlaw** [comment]
As I said, I tried downloading it with rust and trying. I just tried again, doing exactly as you said, but I’m still getting the exact same error message.

**Comment by LunaAmora** [comment]
> EDIT: Fixed it by uninstalling the npm version, but the fact that you are able to do that (and that I was instructed to do that somewhere) should probably be rectified to avoid further confusion.

The [bend](https://www.npmjs.com/package/bend?activeTab=readme) npm package has nothing to do with this project or our company.

Could you share where it was instructed to install it? It would be a misleading information.

**Comment by TheSimicSlaw** [comment]
I was instructed to install it at https://evanw.github.io/bend/ (it’s the second option if you google “bend programming language”). If this is not official, then I would definitely recommend taking action to avoid more people finding it and thinking it’s a valid way to download it.
![Uploading image.jpg…]()

**Comment by developedby** [comment]
Unfortunately a language called Bend already existed and we didn't know about it.
I don't think there's anything we can do about it, they're not doing it maliciously.

Since this other Bend language is abandoned it will eventually get completely shadowed by our Bend, so I don't think that's a huge concern.
