### ISSUE TITLE
double star (**) does not exponentiate, and doesn't give error

### ISSUE THREAD

**Issue by torjusik** [HigherOrderCO/Bend#444]
**Describe the bug**
As stated, double star (**) does not exponentiate, and doesn't give error. instead it returns the base.
The GUIDE.md file contains examples that uses **, however it doesn't behave as excpected.

**To Reproduce**
using an example from GUIDE.md:
```
def distance(a, b):
  (ax, ay) = a
  (bx, by) = b
  dx = bx - ax
  dy = by - ay
  return (dx * dx + dy * dy) ** 0.5

def main():
  return distance((10.0, 10.0), (20.0, 20.0))
```
Result: 200.000

**Expected behavior**
Either it should give correct Result: 14.142 or raise an error for not using ^ 
I prefer it working if it is supposed to be similar to python.
Also the guide should be updated.

**Desktop (please complete the following information):**
 - OS:   [Windows 10, WSL2]
 - CPU: [Intel i5-9600k]
 - GPU: [ RTX 1070]
 - Cuda Version [12.1.0]

**Additional context**
I just installed bend today to try it out through WSL.

**Comment by hakrackete** [comment]
similar setup here, also using WSL. It seems that most of the examples in GUIDE.md are not working.

**Comment by imaqtkatt** [comment]
This is actually a problem in an inet level transformation making the pair `(10.0, 10.0)` reduce to `10.0`. We'll fix that.

**Comment by developedby** [comment]
#448 fixes this. The problem is that the order of the operators was getting inverted when the second argument of ** was a number
