### ISSUE TITLE
Bitwise shfit operations

### ISSUE THREAD

**Issue by MrOnlineCoder** [HigherOrderCO/Bend#446]
**Is your feature request related to a problem? Please describe.**
I am building a recrusive data structure where elements are set as specific bits of a given number in the binary representation. As I understand, Bend does not support bitwise shifts which are usually used in general languages to extract a given bit from a number (at least I have not found it in the docs):

```c
(num >> bit) & 1 
```

**Describe the solution you'd like**
C-like regular syntax

**Comment by developedby** [comment]
Already added, but I guess I forgot to update the docs

**Comment by MrOnlineCoder** [comment]
@developedby pardon me, was it added to some of the recent versions? I've downloaded latest bend like last week and it didn't compile with ">>" expression

```bash
Errors:
In program.bend :
- expected: expression
- detected:
  17 |       bit_value =   (nf >> current_bit) & 1
```

**Comment by LunaAmora** [comment]
> @developedby pardon me, was it added to some of the recent versions? I've downloaded latest bend like last week and it didn't compile with ">>" expression
> 
> ```shell
> Errors:
> In program.bend :
> - expected: expression
> - detected:
>   17 |       bit_value =   (nf >> current_bit) & 1
> ```

Yes, I believe it was implemented in the version 0.2.11 2 days ago

**Comment by MrOnlineCoder** [comment]
Thanks @LunaAmora, didn't expect updates to happen so fast - re-installing bend fixed the issue, at least with the bitshifts themselves

**Comment by MrOnlineCoder** [comment]
Hmm, after installing the latest release 0.2.18, I've got the user-friendly errors and seems the HVM (?) itself is not able to parse the bitshift operation:
```
thread 'main' panicked at /Users/mronlinecoder/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hvm-2.0.9/src/main.rs:73:62:
PARSE_ERROR
- expected: ]
- detected:
  19 | @make_func__bend0__C0 = (* (c ({d $([>>] $(a $([&1] b)))} ({$([+1] e) a} g))))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Errors:
Failed to parse result from HVM.
```

**Comment by LunaAmora** [comment]
Please update you HVM too, in the error it shows it still is using the 2.0.9 version.
