### ISSUE TITLE
Add documentation on builtin types and functions

### ISSUE THREAD

**Issue by developedby** [HigherOrderCO/Bend#453]
**Is your feature request related to a problem? Please describe.**
Currently builtins are each explained in documentation (lists, strings, etc), but there is nowhere that actually lists all the builtins and explains what they are for.
Everything is sort of hidden in `builtins.bend`.

**Describe the solution you'd like**
A document explaining each builtin.

**Describe alternatives you've considered**
Somehow making `builtins.bend` accessible for users, like automatically generating documentation from programs ala doxygen, docs.rs, etc.

**Additional context**
Users have complained about this.
There's actually hidden features in the builtins (maps).

**Comment by Sipher** [comment]
Wrote a .md file to help out, not sure where to add in the Readme, i will push a PR and if necessary I can edit
