### ISSUE TITLE
Subtraction creating invalid HVM program

### ISSUE THREAD

**Issue by amaljohn2304** [HigherOrderCO/Bend#459]
### Reproducing the behavior

Code:
def fnu(a):
  return a - 1

def main():
  return fnu(32)

Error:
1.Failed to parse result from HVM.
Output from HVM was:
"thread 'main' panicked at /home/akjohn2304/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hvm-2.0.13/src/main.rs:73:62:\n\u{1b}[1mPARSE_ERROR\n- expected: \u{1b}[0moperator symbol\u{1b}[1m\n- detected:\n\u{1b}[0m\u{1b}[0m  1 | @fnu = ($([\u{1b}[4m\u{1b}[31m:\u{1b}[0m-1] a) a)\u{1b}[0m\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n""exit status: 101"""

However the same thing works with addition operator

### System Settings

Example:
 - Bend:0.2.11
 - OS: Ubuntu (22.04.3 LTS) run on WSL on WIndows 11

**Comment by LunaAmora** [comment]
Can you try updating HVM and Bend? This was because Bend 0.2.11 needed a feature in HVM 2.0.14 or above.

**Comment by amaljohn2304** [comment]
Yes the hvm update worked. Thanks
