### ISSUE TITLE
Program result prints function name rather than value

### ISSUE THREAD

**Issue by Gadersd** [HigherOrderCO/Bend#493]
### Reproducing the behavior

Running `bend run test.bend` on
```bend
def get_string():
  return "Hello, World!"

def main():
  val = get_string()
  return val
```
yields `Result: get_string` rather than `Result: "Hello, World!"`.

### System Settings

 - hvm v2.0.16
 - bend-lang 0.2.18
 - OS: Linux (Ubuntu 22.04)

**Comment by developedby** [comment]
Closed by #548
