### ISSUE TITLE
Change the monadic block syntax

### ISSUE THREAD

**Issue by developedby** [HigherOrderCO/Bend#494]
Although haskell programmers will dislike it, we think it's better for monadic blocks to have a different syntax.
Due to the strictness requirements of HVM and lazy refs, we'll probably not be able to make every single monad work, so this is also a good extra indication of that.

I propose changing the `do` keyword to `with`.
```py
with IO:
  a <- input()
  b <- print(String/concat("Hello, ", a))
  ...
```
Most monads also define a sequential order of operations, so we shouldn't incentivize to use them too too much, only when it's appropriate.

We should also add a Monad/pure syntax, and I propose `wrap` since it's somewhat intuitive, even to people who are not familiar with the theory behind it.
```
with IO:
  a <- ...
  ...
  return wrap(x)
```
That desugars to `Monad/wrap`, a call to the Monad unit function (also called "pure" in other languages)

**Comment by samueldurantes** [comment]
> ..., we'll probably not be able to make every single monad work, so this is also a good extra indication of that.

Why won't every single monads work?

> I propose wrap since it's somewhat intuitive, even to people who are not familiar with the theory behind it.

Indeed, people unfamiliar with the theory behind it may find the keyword `pure` confusing, but `wrap` also brings this feeling.

Why not name it `return`?

**Comment by developedby** [comment]
> Why won't every single monads work?
If you have a program like
```
def Z(x1, x2):
do Result:
  a <- X(x1)
  b <- Y(x2)
  c <- Z(a, b)
  ...
```
This is converted to ```(Result/bind (X x1) @a (Result/bind (Y x2) @b (Result/bind (Z a b) ...)```
Note that the call to `(Z a b)` is not a combinator and so cannot be converted to a lazy reference. This will cause Z to be expanded infinitely.
For this to actually work, we need to do some transformation on this term that will convert it into ```(...(Result/bind @a @b (Z a b) ...)```.
I haven't yet found a transformation that works on every possible monad, although I have some good directions to explore.


> Why not name it `return`?
Because `return` already returns
