### ISSUE TITLE
[CANNOT INSTALL] Bend-lang compilation fails

### ISSUE THREAD

**Issue by ToXP** [HigherOrderCO/Bend#496]
### Reproducing the behavior

Toolchain Setup: 
'rustup' and 'nightly toolchain' installed via Homebrew on Mac OS (Intel) (not direct 'rustup' Rust installation, i.e., cannot run 'cargo _+nightly_ install <package>')

Bend-lang Installation: 
_$ rustup run nightly cargo install bend-lang_

When downloading/compiling the Bend-lang crate:
-–> Compilation fails (SEE attached screenshot).

### System Settings

![bend-lang--compilation-failure--stacktrace](https://github.com/HigherOrderCO/Bend/assets/70902105/3a30592f-1148-432b-b7c2-d8aa89e6ba36)
 - Bend: [e.g. 0.2.18]
 - OS: [MacOS 10.15.7]
 - CPU: [Dual-Core Intel Core i5]

**Comment by tensor-programming** [comment]
Looks like you are using the stable release of rust.  Instead you should use the `cargo +nightly install bend-lang` commands rather then running it via rustup.

**Comment by ToXP** [comment]
Hello 'tensor-programming' and thanks, quote:
> Looks like you are using the stable release of rust. 

Well, it doesn't seem so - actually I tried to explain before at the previous Toolchain Setup: [description]. 

Please, look at this new screenshot, which shows the results of: 
_$ rustup show_   : the 'nightly' toolchain is the 'default'
_$ cargo +nightly install bend -lang_ : it results in an error. 

The only way I found to run 'cargo' through the 'nightly' toolchain is then: 
_$ rustup run nightly cargo install bend-lang_

This bypasses the current Homebrew Rust installation, which is vs. 1.78.0, while the 'nightly' is vs. 1.80.0.

So maybe the root cause of the missed compilation is elsewhere?
![rustup-and-cargo-behavior](https://github.com/HigherOrderCO/Bend/assets/70902105/20bf1de7-9c3a-4a63-86b3-4fea03c52cf3)

**Comment by kings177** [comment]
there seems to be a problem with the nightly-1.80 version of rust, can you try cloning this repo and doing `cargo install --path .` please? or changing your rust version to any other than 1.80 to see if it works.

**Comment by ToXP** [comment]
Hello 'kings177', quote: 
>  can you try cloning this repo and doing cargo install --path . please?

- I cloned this repo on locale
- then I run both: 
  - _$ cargo install --path ._ (i.e., calling 'cargo' from vs. 1.78.0 'stable' release), and
  - _$ rustup run nightly cargo install --path ._ (i.e., calling 'cargo' from vs. 1.80.0 'nightly' release)

Unfortunately both the outcomes were negative: the output gives the same compilation errors in the stacktrace shown before (first screenshot). 

The hypothesis of having troubles with Rust 'nightly 1.80.0 seems to get more consistent. I will try to verify through another Rust 'nightly' vs. and see if the outcome changes. (to be updated)

**Comment by IceWind233** [comment]
I encounter same problem when i compile bend-lang with `WSL` and `cargo 1.80.0-nightly` 😢😢

**Comment by developedby** [comment]
The lastest published version of Bend (0.2.22) no longer depends on rust nightly. Can you try updating?

**Comment by IceWind233** [comment]
> The lastest published version of Bend (0.2.22) no longer depends on rust nightly. Can you try updating?

well done. i finished compiling `bend-lang` with wsl.👏👏

**Comment by developedby** [comment]
@ToXP can you confirm as well?

**Comment by ToXP** [comment]
Hello '_developedby_', 

awesome! Bend Vs. 0.2.22 compiled smoothly as butter. 

Thank you guys, the issue is 'solved'.

**Comment by ToXP** [comment]
Hello '_developedby_', 

awesome! Bend Vs. 0.2.22 compiled smoothly as butter. 

Thank you guys, the issue is 'solved'.
