### ISSUE TITLE
Doesn't find CUDA on Nvidia PRIME Laptop 

### ISSUE THREAD

**Issue by FutureExcited** [HigherOrderCO/Bend#532]
### Reproducing the behavior

Example:
 Running command: bend run-cu helloworld.bend
 With code: Your sorter.bend [code](https://gist.github.com/VictorTaelin/face210ca4bc30d96b2d5980278d3921) 
 Error... `CUDA runtime not available!
 If you've installed CUDA and nvcc after HVM, please reinstall HVM.
Errors:
Failed to parse result from HVM.`
 Expected behavior: run

### System Settings

Example:
 - HVM: 20.17
 - Bend: 0.2.27
 - OS: Linux Pop!_OS 22.04
 - CPU: Intel i5-12500H
 - GPU: RTX 4060
 - Cuda Version 12.4

### Additional context

 Laptop with an iGPU and a dGPU RTX 4060
 Running this on Pop!_OS, which is famous for their laptop nvidia drivers support.
 nvidia-smi finds CUDA, and running local LLM models with Llama is working well with no config. 
Additional info: running this on a laptop screen, not external monitor. Doesn't work with both hybrid mode, and Nvidia Graphics mode set via systems76-power (even though the whole system begins to run on dGPU).

nvidia-smi output:
![image](https://github.com/HigherOrderCO/Bend/assets/113827671/383f1dba-0380-4fbc-a3ef-21dba761ee5e)

 Tried reinstalling the HVM - doesn't work.

**Comment by edusporto** [comment]
Just to be sure, have you tried running `nvcc` in a terminal to be sure that it's installed and in your `PATH` variable?

**Comment by FutureExcited** [comment]
☠️☠️☠️ it was not installed

ON THE BRIGHT SIDE IT WORKS AFTER THIS AND REINSTALLING HVM LETS GOOOOO

Thanks, would be cool to have an installation checklist for noobs, and checks to see if it's installed.

You language is crazy, good luck in development, and I will definitely follow along with your updates!

**Comment by edusporto** [comment]
Thanks, glad it worked!
