### ISSUE TITLE
Tuples should be defined by commas(like python), not by parentheses

### ISSUE THREAD

**Issue by TimotejFasiang** [HigherOrderCO/Bend#554]
**Is your feature request related to a problem? Please describe.**
In python, it is the commas, not the parentheses, that define the tuple. Not sure whether it's worth the effort to change this or whether there is a specific reason that it has to be this way.

**Describe the solution you'd like**
Having tuples be defined by commas and not by parentheses.

**Describe alternatives you've considered**
Leaving it the way it is, with tuples being defined by parentheses.

**Comment by developedby** [comment]
There is no specific reason and I don't think it'll cause any syntax conflict.

I just forgot about this case in Python.
