### ISSUE TITLE
Unexpected return value in Match statement for non-matching cases

### ISSUE THREAD

**Issue by TimotejFasiang** [HigherOrderCO/Bend#559]
### Reproducing the behavior

 ```
def main:
  input = 3

  match input:
    case List/Cons:
      return "list"
    case List/Nil:
      return "empty list"
```
 This code returns 3 even though I don't have ```return 3``` anywhere in the code.
 It should not return anything in this case.

### System Settings

 - HVM: HVM 2.0.19
 - Bend: 0.2.33
 - OS: Linux (Ubuntu 24.04 LTS)
 - CPU: AMD Ryzen 5 3600
 
 Same unexpected result with ```run``` and ```run-c```

**Comment by developedby** [comment]
Matching on the wrong type of value will break your program. This is the expected behaviour.

When we implement a type system this will be a compilation error
