### ISSUE TITLE
Using C or Rust Libraries in Bend

### ISSUE THREAD

**Issue by rawhuul** [HigherOrderCO/Bend#587]
Hi,
Thanks for Bend, its **massively** impressive.

Most computational heavy library in python are written in C, like numpy, tf, pandas, etc. This is not the case for Bend, but ability to use already build library would benefit the whole bend ecosystem. 
Is it possible to use them?? Maybe via FFI, but this will only applicable to C ABI, libraries like Polars written in Rust would need extra work to port here.

**Comment by developedby** [comment]
Yes, this is  planned. 
Closing as duplicate of https://github.com/HigherOrderCO/Bend/issues/350. See there for more information
