### ISSUE TITLE
Add IO/FS/flush function to prelude

### ISSUE THREAD

**Issue by developedby** [HigherOrderCO/Bend#598]
HVM now exposes a file flushing primitive (https://github.com/HigherOrderCO/HVM/pull/392), so we should create a function in the bend prelude to expose it to the users, like is done for the other file primitives.

**Comment by developedby** [comment]
Of course!
If you look at https://github.com/HigherOrderCO/Bend/pull/593/files, you can see more or less what you need to do, just update builtins.bend, builtins.md and changelog.md.
The function should be called `IO/FS/flush`, receive a file descriptor as argument and return nothing, like `IO/FS/write` returns nothing.

To test it you have to use the main branch from HVM since flush is not in a rleased version yet

**Comment by bhavik-goplani** [comment]
Sounds good, thanks!

**Comment by developedby** [comment]
Closed by #619
