### ISSUE TITLE
Returning a String in main outputs a Result: 1 instead of the string when using run-cu

### ISSUE THREAD

**Issue by phazejeff** [HigherOrderCO/Bend#610]
### Reproducing the behavior

I'm running a simple hello world program
```bend
def main():
  return "hello world"
```

When running with `run` or `run-c` it correctly outputs "Result: hello world".
But, when running with `run-cu` it outputs "Result: 1"
Weirdly, when running run-cu with the `--verbose` flag, it says `(main) = "hello world"` at the end of it, despite it giving `Result: 1` https://pastebin.com/tPW3VjfY

### System Settings

 - HVM: 2.0.19
 - Bend: 0.2.33
 - OS: WSL2 Ubuntu 20.04.6 on Windows 10
 - CPU: AMD Ryzen 7 7700X
 - GPU: RTX 3060 12GB
 - Cuda Version 12.5 (Also tested with 12.4)

**Comment by mikemcqueen** [comment]
exact same issue

- HVM: 2.0.19
- Bend: 0.2.33
- OS: WSL2 Ubuntu 22.04.3 on Windows 11
- CPU: intel I7-12700 laptop
- GPU: RTX 4080 laptop
- Cuda: 12.5 (Also tested with 12.4)

**Comment by developedby** [comment]
https://github.com/HigherOrderCO/HVM/pull/401 should fix this.

**Comment by phazejeff** [comment]
> [HigherOrderCO/HVM#401](https://github.com/HigherOrderCO/HVM/pull/401) should fix this.

Just tested with hvm 2.0.21 and can confirm that this has fixed the issue
