### ISSUE TITLE
Don't have the Rust runtime as the default for `bend run`

### ISSUE THREAD

**Issue by developedby** [HigherOrderCO/Bend#620]
**Is your feature request related to a problem? Please describe.**
The Rust runtime is the reference implementation, but it's slow and doesn't have IO.
It's confusing for new users.

**Describe the solution you'd like**
Change `bend run` command into `bend run-rs`.

**Describe alternatives you've considered**
* Also making `run` default to `run-c`.

**Comment by bhavik-goplani** [comment]
@developedby I'd like to work on this issue. Is there anything I should know before working on this?

**Comment by developedby** [comment]
You need to update the cli tests to the new command. in `tests/golden_tests/cli/*`

To run the tests you need to install cargo-insta `cargo install cargo-insta`, run them with `cargo insta test` and then update the snapshots with `cargo insta review` if anything changed.

**Comment by imaqtkatt** [comment]
fixed #630
