### ISSUE TITLE
Creating Rust packages and import to Bend

### ISSUE THREAD

**Issue by AndreyMihaylovDron** [HigherOrderCO/Bend#653]
Hi, is it possible today to create package on rust and then import to bend as library or something?

**Comment by developedby** [comment]
Yes, but you need export your Rust function into a dynamic library with C interfaces, and wrap your functions with adapters for communicating and converting your values for the HVM.

You can read how to do that here https://github.com/HigherOrderCO/Bend/blob/main/docs/ffi.md.
We're still working on refining the ffi interfaces, so you can expect it to become easier to write your bend libraries in other languages in the future

**Comment by AndreyMihaylovDron** [comment]
This is cool, thanks!
