### ISSUE TITLE
type checking does not play well with imports

### ISSUE THREAD

**Issue by NoamDev** [HigherOrderCO/Bend#722]
### Reproducing the behavior

Example:
 Running command: bend check main.bend
 With code:

**a.bend**
```
type MyType:
  A

Foo: MyType -> MyType

(Foo MyType/A) = MyType/A
 ```
 
**main.bend**
```
from a import *
main = "hello world"
```
 
 Error.:
```
Errors:
In a :
In definition 'a/Foo':
  Type Error: Expected function type '(a/MyType -> a/MyType)' but found '(MyType -> a/MyType)'.
```
 Expected behavior....
The code should check

### System Settings

Example:
 - HVM: hvm 2.0.22
 - Bend: bend-lang 0.2.37-alpha.1

**Comment by developedby** [comment]
Likely missing a rename of imports somewhere, I'll have a look.

**Comment by NoamDev** [comment]
@developedby did you take a look? 😅
sorry, if it's just not you prority, I just thought you may have forgotten

**Comment by developedby** [comment]
Sorry, I did forget since I was focused on something else. The issue was actually not that hard, we just store the name of the types redundantly and were only updating one of the places.

**Comment by NoamDev** [comment]
@developedby Now this doesn't work...

** a.bend **
```
type MyType:
  A {data: u24}
  B {data: u24}

Foo: MyType -> MyType

(Foo (MyType/A a)) = (MyType/A a)
(Foo (MyType/B b)) = (MyType/B b)
```

** main.bend**
```
from a import *
main = "hello world"
```

```
> bend check main.bend
Errors:
In a :
In definition 'a/Foo':
  Unbound constructor 'MyType/A' in pattern matching rule.
  Unbound constructor 'MyType/B' in pattern matching rule.
```
